# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate
safe: false
exclude:
  - "/vendor/"

# Site settings
title: "메모로그"
subtitle: "에버노트 그만쓰려고 만든 메모장 블로그"
email: seolminsu90@gmail.com
name: minsu seol
description: >
  test
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/blog" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: true
highlightjs_theme: "vs2015" #"monokai-sublime"

# Pagination Settings
paginate: 10                  # 페이징 처리 개수
paginate_path: "/page:num/"   # URL 규칙

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

descriptions:
  - BACKEND
  - FRONTEND
  - DATABASE
  - SERVER
  - SHELL
  - CICD
  - ETC

social:
  - name: GitHub
    icon: github
    username: "msseol (blog)"
    url: https://github.com/msseol
    desc: GitHub
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
#protocols:
#    os_repo: "https://github.com/bencentra/centrarium.com"
#    os_rcs_type: "git"
#    os_src: "git@github.com:bencentra/centrarium.com.git"
